import Head from 'next/head'
import Header from '../components/Header'
import Register from '../components/Register'
import RegistrationForm from '../components/RegistrationForm'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hype Heads</title>
        <meta name="description" content="Generated by create next app" />
        <link href="/favicon.ico" rel="icon" type="text/css" media="all"/>
      </Head>
      {/* Header */}

      <Header/>

      
       
      {/* Registration Form */}
       
      {/* <RegistrationForm/> */}
      <Register/>

      

    </div>
    
  )
}
