import Head from 'next/head'
import Header from '../components/Header'
import RegistrationForm from '../components/RegistrationForm'


export default function Home() {
  return (
    <div>
      <Head>
        <title>HypeHeads</title>
        <meta name="description" content="Generated by create next app" />
        <link href="/favicon.ico" rel="icon" type="text/css" media="all"/>
      </Head>
      {/* Header */}

      <Header/>
       {/* Registration Form */}
      <RegistrationForm/>

      

    </div>
    
  )
}
