import Head from 'next/head'
import Header from '../components/Header'
import RegistrationForm from '../components/RegistrationForm'

export default function Home() {
  return (
    <div>
      <Head>
        <title>CapStone Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}

      <Header/>
       {/* Registration Form */}
      <RegistrationForm/>



    </div>
  )
}
